//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class avtor
    {
        public avtor()
        {
            this.book = new HashSet<book>();
        }
    
        public int id_avtor { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.DateTime> deathdate { get; set; }
    
        public virtual ICollection<book> book { get; set; }
    }
}
