//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.historiReader = new HashSet<historiReader>();
        }
    
        public int ID_book { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int id_avtor { get; set; }
        public int id_janor { get; set; }
        public int id_sheff { get; set; }
    
        public virtual avtor avtor { get; set; }
        public virtual janor janor { get; set; }
        public virtual shelf shelf { get; set; }
        public virtual ICollection<historiReader> historiReader { get; set; }
    }
}
