//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class historiReader
    {
        public int id { get; set; }
        public int Id_book { get; set; }
        public int id_readerticket { get; set; }
        public Nullable<System.DateTime> datestart { get; set; }
        public Nullable<System.DateTime> dateend { get; set; }
        public int id_sotrydnik { get; set; }
        public string coment { get; set; }
    
        public virtual book book { get; set; }
        public virtual readerticket readerticket { get; set; }
        public virtual sotrydnik sotrydnik { get; set; }
    }
}
