//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class janor
    {
        public janor()
        {
            this.book = new HashSet<book>();
        }
    
        public int id_janor { get; set; }
        public string janor1 { get; set; }
    
        public virtual ICollection<book> book { get; set; }
    }
}
