//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DbConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoEntities : DbContext
    {
        public DemoEntities()
            : base("name=DemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<avtor> avtor { get; set; }
        public DbSet<book> book { get; set; }
        public DbSet<gender> gender { get; set; }
        public DbSet<historiReader> historiReader { get; set; }
        public DbSet<janor> janor { get; set; }
        public DbSet<post> post { get; set; }
        public DbSet<reader> reader { get; set; }
        public DbSet<readerticket> readerticket { get; set; }
        public DbSet<shelf> shelf { get; set; }
        public DbSet<sotrydnik> sotrydnik { get; set; }
    }
}
