//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public post()
        {
            this.sotrydnik = new HashSet<sotrydnik>();
        }
    
        public int id_post { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<sotrydnik> sotrydnik { get; set; }
    }
}
