//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class reader
    {
        public reader()
        {
            this.readerticket = new HashSet<readerticket>();
        }
    
        public int id_reader { get; set; }
        public string FIO { get; set; }
        public string phone { get; set; }
        public string gmail { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
    
        public virtual ICollection<readerticket> readerticket { get; set; }
    }
}
