//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class readerticket
    {
        public readerticket()
        {
            this.historiReader = new HashSet<historiReader>();
        }
    
        public int id_readerticket { get; set; }
        public int Id_reader { get; set; }
        public Nullable<System.DateTime> dateregist { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
    
        public virtual ICollection<historiReader> historiReader { get; set; }
        public virtual reader reader { get; set; }
    }
}
