//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class sotrydnik
    {
        public sotrydnik()
        {
            this.historiReader = new HashSet<historiReader>();
        }
    
        public int id_sotrydnik { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public int id_post { get; set; }
        public string mail { get; set; }
        public string phone { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int id_gender { get; set; }
    
        public virtual gender gender { get; set; }
        public virtual ICollection<historiReader> historiReader { get; set; }
        public virtual post post { get; set; }
    }
}
